// Mock Data for Family Business
// Auto-generated by bitable-sync - DO NOT EDIT MANUALLY

export interface StoreInfo {
    name: string;
    phone: string;
    qrCodeUrl: string;
}

export interface MediaItem {
    type: 'video' | 'image';
    url: string;
    title?: string;
    duration?: number; // for images, duration in ms
}

export interface Product {
    id: string;
    name: string;
    description: string;
    price: number;
    image: string;
    categoryId: string;
}

export interface Category {
    id: string;
    name: string;
    icon?: string;
}

// Get base URL for assets (works with GitHub Pages subpath)
const BASE_URL = import.meta.env.BASE_URL;

// Store Information
export const storeInfo: StoreInfo = {
    name: '伟盛酒业',
    phone: '15936229925',
    qrCodeUrl: `${BASE_URL}images/qrcode.jpg`
};

// Media playlist - videos and images for the ad display
export const mediaPlaylist: MediaItem[] = [
    {
        type: 'video',
        url: `${BASE_URL}videos/古越龙山-品牌宣传片/index.m3u8`,
        title: '古越龙山 品牌宣传片',
        duration: 5000
    },
    {
        type: 'video',
        url: `${BASE_URL}videos/古越龙山-方文山曲/index.m3u8`,
        title: '古越龙山 方文山曲',
        duration: 5000
    },
    {
        type: 'video',
        url: `${BASE_URL}videos/古越龙山-只此青绿/index.m3u8`,
        title: '古越龙山 只此青绿',
        duration: 5000
    },
];

// Categories - 黄酒分类
export const categories: Category[] = [
];

// Products - 黄酒商品
export const products: Product[] = [
];

// Helper function to get products by category
export function getProductsByCategory(categoryId: string): Product[] {
    return products.filter(p => p.categoryId === categoryId);
}

// Helper function to get product by id
export function getProductById(productId: string): Product | undefined {
    return products.find(p => p.id === productId);
}
